### ISSUE TITLE
magre encoder and decoder pls

### ISSUE THREAD

**Issue by matrix3d** [soiaf/haXe-WavPack-encoder#2]

**Comment by soiaf** [comment]
Sorry - I don't understand what you're asking for - what is magre?

**Comment by matrix3d** [comment]
merge the encoder and decoder.
bcs i have a project need both decoder and encoder.but now some code not the same.

**Comment by matrix3d** [comment]
make haXe-WavPack-encoder and haXe-WavPack-decoder as haxe-wavpack.

**Comment by soiaf** [comment]
I have now updated the WavPack encoder code so that it works with Haxe 3 - this means that both the decoder and encoder should work fine now with Haxe 3.
I do not plan on merging the 2 code bases together however.
