### ISSUE TITLE
how decoder and encoder realtime?

### ISSUE THREAD

**Issue by matrix3d** [soiaf/haXe-WavPack-encoder#3]
we want to do a realtime chat.
but the wav size too big?
so the wavpack?

**Comment by soiaf** [comment]
There is going to be a certain amount of latency between recording the audio, converting it to a minimum usable size and then transmitting it - I can't say whether this latency will be too much to be acceptable for realtime chat.
WavPack will definitely compress the data used and you should be able to get fairly low latency, but I can't say whether it will be low enough for the usage you have planned.
There is an even lower latency version of WavPack, but I think this code is only in C form. I don't know its current state, you would need to directly contact the creator of WavPack.
